# Generated by Django 4.1.1 on 2023-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applynow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=50)),
                ('mobilenumber', models.IntegerField(max_length=50)),
            ],
        ),
    ]
