# Generated by Django 4.1.1 on 2023-04-01 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_applynow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.IntegerField(max_length=50)),
                ('loantype', models.CharField(choices=[('newhome', 'newhome'), ('balancetransfer', 'balancetransfer')], max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('property', models.CharField(max_length=50)),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
