# Generated by Django 4.1.1 on 2023-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_personalloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalloan',
            name='employeetype',
            field=models.CharField(choices=[('salaried', 'salaried'), ('selfsalaried', 'selfsalaried')], max_length=50),
        ),
    ]
