# Generated by Django 4.1.1 on 2023-04-05 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_alter_personalloan_employeetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buisnessloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('amount', models.IntegerField(max_length=50)),
                ('employed', models.CharField(max_length=50)),
                ('turnover', models.CharField(max_length=50)),
                ('mobilenumber', models.IntegerField(max_length=10)),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
